// Code generated by mockery v2.3.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// HTTPClientProvider is an autogenerated mock type for the HTTPClientProvider type
type HTTPClientProvider struct {
	mock.Mock
}

// Request provides a mock function with given fields: _a0, _a1, _a2, _a3, _a4
func (_m *HTTPClientProvider) Request(_a0 string, _a1 string, _a2 map[string]string, _a3 []byte, _a4 map[string]string) (int, []byte, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3, _a4)

	var r0 int
	if rf, ok := ret.Get(0).(func(string, string, map[string]string, []byte, map[string]string) int); ok {
		r0 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 []byte
	if rf, ok := ret.Get(1).(func(string, string, map[string]string, []byte, map[string]string) []byte); ok {
		r1 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]byte)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string, string, map[string]string, []byte, map[string]string) error); ok {
		r2 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
